# -*- coding: utf-8 -*-
"""strong number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KASY7uqmrEhnVtnk_o7eZ2Z7J6Tl0olM
"""

import math
num=int(input("Enter the number: "))
fact=0
n=num
while n>=1:
  digit=n%10
  fact=fact+math.factorial(digit)
  n//=10
print(fact)
print(num)
if num==fact:
  print("It is a strong number")
else:
  print("It is not a strong number")

import math
num=145
fact=0
n=num
while n>=1:
  digit=n%10
  fact=fact+math.factorial(digit)
  n//=10
print(fact)
print(num)
if num==fact:
  print("It is a strong number")
else:
  print("It is not a strong number")